### ISSUE TITLE
chromium url possibly broke

### ISSUE THREAD

**Issue by Willbrainnes** [Noxde/glyph-redeemer#1]
I tried to run it and got and got this error. I believe it's the chromium download url that's dead 

![image](https://github.com/Noxde/glyph-redeemer/assets/25065774/d92c0d9e-e3e3-4fe4-9382-6b46d3014b69)

**Comment by Noxde** [comment]
Thanks for making this issue, managed to fix it by updating puppeteer and the chromium version, I will push the changes and make the new release in a bit

**Comment by Noxde** [comment]
Just uploaded the [new release](https://github.com/Noxde/glyph-redeemer/releases/tag/1.2.3) fixing that issue, please download that one and give it a shot. Thanks again for making the issue and for wanting to try Glyph Redeemer
