### ISSUE TITLE
Cant login (cookie json issue

### ISSUE THREAD

**Issue by Denryuu2** [Noxde/glyph-redeemer#2]
Iv followed the instruction and retested a few times. the issue i seem to be having is the extension for the cookies saves the user and that as "remember_login"

Im not sure what values and such i need to change for the cookies json to work properly.

I logged out and unchecked "remember password" as i thought this was the cause, it removed the paragraph of text, but still not solution.

**Comment by Noxde** [comment]
This could be related to the changes cookie editor has received a while back, when prompted with this did you click on "This site"?
![image](https://github.com/Noxde/glyph-redeemer/assets/70549780/be0e5432-1705-44e8-8eb2-5b491ea3c90d)

If you did then that's the problem, re install cookie editor and click on "All sites" and it should work. Let me know if that fixes it

**Comment by Denryuu2** [comment]
Ok, that was the problem. Thank you. logged in fine.

**Comment by Noxde** [comment]
> This could be related to the changes cookie editor has received a while back, when prompted with this did you click on "This site"? ![image](https://private-user-images.githubusercontent.com/70549780/326211106-be0e5432-1705-44e8-8eb2-5b491ea3c90d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNTMwODMsIm5iZiI6MTcxNDI1Mjc4MywicGF0aCI6Ii83MDU0OTc4MC8zMjYyMTExMDYtYmUwZTU0MzItMTcwNS00NGU4LThlYjItNWI0OTFlYTNjOTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDIxMTk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiNTQ4OTMwZGZlMWRkMzdhOTlmNTBlYTIwMmQ0YzU4NTFhOWRlOWJiNWU5NTViNGQyMGJjOGFiMGU5MmFjZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5RhPwzA60F4ItbR3zfs6UFMZBGLO_ZtATXI6weX0ELs)
> 
> If you did then that's the problem, re install cookie editor and click on "All sites" and it should work. Let me know if that fixes it

Added this image to the readme as well
