### ISSUE TITLE
PLS HELP

### ISSUE THREAD

**Issue by Asharm123** [Noxde/glyph-redeemer#5]
Hi, the program breaks at step 5 of "Usage" for me. I have the cookies all set up but it's giving me the first attachment when I try to run the .exe, and the second after I hit enter, no matter how many times I run it.
![image](https://github.com/user-attachments/assets/686f30e9-2c77-4f55-be2a-ed87f85f0961)
![image](https://github.com/user-attachments/assets/325b66ab-70b9-4c24-a195-30eb28e38e50)

**Comment by Noxde** [comment]
Im sorry about that, thanks for letting me know. I will look into it

**Comment by Noxde** [comment]
I will delete the latest release so you can still use it, if it tries to update after i delete the latest release download the 1.3.2 version

**Comment by Noxde** [comment]
Reuploaded the latest release [1.3.3](https://github.com/Noxde/glyph-redeemer/releases/tag/1.3.3)

**Comment by Asharm123** [comment]
Thanks! It worked, but it ran into captchas it couldn't get through after a few codes
![image](https://github.com/user-attachments/assets/a5518bae-c6a0-4118-ae81-1754c8f1e127)

**Comment by Noxde** [comment]
Hey sorry, i didnt get any notifications for this. When you get the captchas you should not use it for a day or so because you are being rate limited, it should go away after some time so probably a day or 2 maybe

**Comment by Noxde** [comment]
Hey @Asharm123, just wanted to check in before closing this issue. Have you been able to redeem the glyphs?

**Comment by steve1316** [comment]
@Noxde I don't know about the other guy, but the program works and I was able to claim the glyphs.

**Comment by Noxde** [comment]
> @Noxde I don't know about the other guy, but the program works and I was able to claim the glyphs.

Glad to know that it worked fine for you, I will close this issue now since he hasnt answered in a week and it only was a rate limit issue
