### ISSUE TITLE
Cookies incorrect eventhough they are correct?

### ISSUE THREAD

**Issue by szesd** [Noxde/glyph-redeemer#6]
![image_2024-10-04_140654036](https://github.com/user-attachments/assets/23a29b75-140d-441d-b9be-fee5bc138384)

**Comment by Noxde** [comment]
They could have expired, have you tried updating them?

**Comment by Noxde** [comment]
Have you been able to fix this?

**Comment by szesd** [comment]
I reset the cookies. Logged out and in but it still doesn’t work. I
reinstalled the whole thing too :(

**Comment by Noxde** [comment]
Try deleting the cookies extension and installing it again, make sure to give it permission to all sites and try again

**Comment by szesd** [comment]
I’ll do that when I get home :) In a few hours

**Comment by szesd** [comment]
yeah still nothing dude. idk what to do

**Comment by Noxde** [comment]
What platform is your account from? I tried with warframe and ps4 accounts and worked fine, I don't really know what could be the problem if you already gave permission on all sites to the extension

**Comment by szesd** [comment]
It’s a Xbox account but I linked it to my steam

**Comment by Noxde** [comment]
Try logging in with the xbox account on the warframe site and then exporting the cookies again, I would assume you were logging in using the steam account

**Comment by szesd** [comment]
I was logging in with my regular login. I’ll try that then

**Comment by Noxde** [comment]
Still I dont think that should be a problem, dumb question. Are you saving the cookies.json file? make sure you are but I guess you already are

**Comment by szesd** [comment]
Ill install a diff browser tmr maybe that could fix it?

**Comment by Noxde** [comment]
You could definitely try that but I don't think that should be the issue, what browser are you using right now so I can try it

**Comment by szesd** [comment]
Opera Gx on the current update

**Comment by Noxde** [comment]
I'll install it and let you know

**Comment by Noxde** [comment]
It did work.
![{422162B7-35A7-4C3F-8A68-F378CE8887D5}](https://github.com/user-attachments/assets/4c6be9fa-ee9b-4ad3-8247-79f85d97799d)
Make sure you click on "All sites" when using the extension for the first time and make sure to save the changes to the cookies.json file

**Comment by szesd** [comment]
So i switched to edge and used and logged in on edge and it started
working. :)

**Comment by Noxde** [comment]
Awesome! weird that it wouldn't work in opera for you, closing this then
